DbFirst/DbFirst/Models/Northwind/UmlDiagram.cs
using System;
using System.Collections.Generic;

namespace DbFirst.Models.Northwind
{
    public partial class UmlDiagram
    {
        public int DiagramId { get; set; }
        public string Name { get; set; }
        public string DrawData { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? LastModifed { get; set; }
        public int? UserId { get; set; }
        public int? ModelId { get; set; }

        public OwlModel Model { get; set; }
        public UserAccount User { get; set; }
    }
}

DbFirst/DbFirst/Controllers/UmlDiagramsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbFirst.Models.Northwind;
using System.Xml.Linq;
using DbFirst.Models;
using Newtonsoft.Json;
using UmlDiagramModels;
using System.IO;
using System.Net;

namespace DbFirst.Controllers
{
    public class UmlDiagramsController : Controller
    {
        private readonly NorthwindEntities _context;

        public UmlDiagramsController(NorthwindEntities context)
        {
            _context = context;
        }

        // GET: UmlDiagrams
        public async Task<IActionResult> Index()
        {
            var northwindEntities = _context.UmlDiagram.Include(u => u.Model).Include(u => u.User);
            return View(await northwindEntities.ToListAsync());
        }

        // GET: UmlDiagrams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var umlDiagram = await _context.UmlDiagram
                .Include(u => u.Model)
                .Include(u => u.User)
                .SingleOrDefaultAsync(m => m.DiagramId == id);
            if (umlDiagram == null)
            {
                return NotFound();
            }

            return View(umlDiagram);
        }

        // GET: UmlDiagrams/Create
        public IActionResult Create()
        {
            ViewData["ModelId"] = new SelectList(_context.OwlModel, "ModelId", "Name");
            ViewData["UserId"] = new SelectList(_context.UserAccount, "UserId", "Name");
            return View();
        }

        // POST: UmlDiagrams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DiagramId,Name,DrawData,Created,LastModifed,UserId,ModelId")] UmlDiagram umlDiagram)
        {
            if (ModelState.IsValid)
            {
                _context.Add(umlDiagram);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ModelId"] = new SelectList(_context.OwlModel, "ModelId", "Name", umlDiagram.ModelId);
            ViewData["UserId"] = new SelectList(_context.UserAccount, "UserId", "Email", umlDiagram.UserId);
            return View(umlDiagram);
        }

        // GET: UmlDiagrams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var umlDiagram = await _context.UmlDiagram.SingleOrDefaultAsync(m => m.DiagramId == id);
            if (umlDiagram == null)
            {
                return NotFound();
            }

            var rules = _context.OwlModel.Where(m => m.ModelId == umlDiagram.ModelId).Select(r => r.DefaultDrawData).FirstOrDefault();
            var owlRules = JsonConvert.DeserializeObject<OwlDependenciesRules>(rules);

            ViewData["ModelId"] = new SelectList(_context.OwlModel, "ModelId", "Name", umlDiagram.ModelId);
            ViewData["UserId"] = new SelectList(_context.UserAccount, "UserId", "Email", umlDiagram.UserId);

            var model = new DiagramEditDrawViewModel();
            model.owlRules = owlRules;
            model.umlDiagram = umlDiagram;

            return View(model);
        }

        // POST: UmlDiagrams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DiagramId,Name,DrawData,Created,LastModifed,UserId,ModelId")] UmlDiagram umlDiagram)
        {
            if (id != umlDiagram.DiagramId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {                
                try
                {
                    var modelBeforeEdit = _context.UmlDiagram.Where(m => m.DiagramId == umlDiagram.DiagramId).Select(nm => new { nm.Created, LastModifed=DateTime.Now, nm.Model.ModelId, nm.User.UserId }).FirstOrDefault();
                    umlDiagram.Created = modelBeforeEdit.Created;
                    umlDiagram.LastModifed = modelBeforeEdit.LastModifed;
                    umlDiagram.ModelId = modelBeforeEdit.ModelId;
                    umlDiagram.UserId = modelBeforeEdit.UserId;

                    _context.Update(umlDiagram);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UmlDiagramExists(umlDiagram.DiagramId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ModelId"] = new SelectList(_context.OwlModel, "ModelId", "Name", umlDiagram.ModelId);
            ViewData["UserId"] = new SelectList(_context.UserAccount, "UserId", "Email", umlDiagram.UserId);
            return View(umlDiagram);
        }

        // GET: UmlDiagrams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var umlDiagram = await _context.UmlDiagram
                .Include(u => u.Model)
                .Include(u => u.User)
                .SingleOrDefaultAsync(m => m.DiagramId == id);
            if (umlDiagram == null)
            {
                return NotFound();
            }

            return View(umlDiagram);
        }

        // POST: UmlDiagrams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var umlDiagram = await _context.UmlDiagram.SingleOrDefaultAsync(m => m.DiagramId == id);
            _context.UmlDiagram.Remove(umlDiagram);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UmlDiagramExists(int id)
        {
            return _context.UmlDiagram.Any(e => e.DiagramId == id);
        }

        [HttpPost]
        public ActionResult mytry(DiagramEditDrawViewModel model)
        {
            var rules = _context.OwlModel.SingleOrDefault(o => o.ModelId == model.umlDiagram.ModelId).DefaultDrawData;
            model.owlRules = JsonConvert.DeserializeObject<OwlDependenciesRules>(rules);

            //var userName = _context.UserAccount.Where(u => u.UserId == model.umlDiagram.UserId).FirstOrDefault().Name;
            //var fileName = userName  + "_" + model.umlDiagram.Name + ".json";
            //string path = @"SavedData\" + fileName;
            //var logFile = System.IO.File.Create(path);
            //var logWriter = new System.IO.StreamWriter(logFile);
            //logWriter.WriteLine(model.umlDiagram.DrawData);
            //logWriter.Dispose();

            //string downloadsPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            

            //using (WebClient webClient = new WebClient())
            //{
            //    webClient.DownloadFile(path, getDownloadFolderPath() + @"\myfile.json");
            //}
            //System.IO.File.Delete(path);

            var diagram = DiagramGenerator.DrawedDiagramGenerator.GenerateDiagram(model.umlDiagram.DrawData);
            var x = diagram.IsValid();


            return View();
        }

        public static string getHomePath()
        {
            // Not in .NET 2.0
            // System.Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
            if (System.Environment.OSVersion.Platform == System.PlatformID.Unix)
                return System.Environment.GetEnvironmentVariable("HOME");

            return System.Environment.ExpandEnvironmentVariables("%HOMEDRIVE%%HOMEPATH%");
        }

        public static string getDownloadFolderPath()
        {
            if (System.Environment.OSVersion.Platform == System.PlatformID.Unix)
            {
                string pathDownload = System.IO.Path.Combine(getHomePath(), "Downloads");
                return pathDownload;
            }

            return System.Convert.ToString(
                Microsoft.Win32.Registry.GetValue(
                     @"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders"
                    , "{374DE290-123F-4565-9164-39C4925E467B}"
                    , String.Empty
                )
            );
        }
    }
}

DbFirst/DbFirst/Views/UmlDiagrams/Create.cshtml
@model DbFirst.Models.Northwind.UmlDiagram

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>UmlDiagram</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ModelId" class="control-label"></label>
                <select asp-for="ModelId" class ="form-control" asp-items="ViewBag.ModelId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DbFirst/DbFirst/Views/UmlDiagrams/Delete.cshtml
@model DbFirst.Models.Northwind.UmlDiagram

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UmlDiagram</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DrawData)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DrawData)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastModifed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastModifed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DiagramId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DbFirst/DbFirst/Views/UmlDiagrams/Details.cshtml
@model DbFirst.Models.Northwind.UmlDiagram

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>UmlDiagram</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DrawData)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DrawData)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastModifed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastModifed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.DiagramId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DbFirst/DbFirst/Views/UmlDiagrams/Edit.cshtml
@model DbFirst.Models.DiagramEditDrawViewModel;

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>UmlDiagram</h4>

<hr />

<form asp-controller="UmlDiagrams" asp-action="mytry" method="post">
    <div id="DiagramEditorWithMenu" style="width:100%; height:100%">
        <div id="UmlEditorForm" style="width:100%; float:left">
            <table style="width:100%; height:100%">
                <tr valign="top">
                    <td style="width:20%">
                        <div class="form-group" id="DiagramDrawModeForm">
                            <label class="control-label">Draw Mode</label>
                            @Html.RadioButton("DrawMode", "Node")  Nodes
                            @Html.RadioButton("DrawMode", "Owl")  Dependencies
                        </div>
                    </td>
                    <td style="width:80%">
                        <div class="form-group" id="NodeModeForm" style="display:none">
                            <label class="control-label">Option Mode</label>
                            @Html.RadioButton("NodeDrawMode", "Activity", new { @checked = true })  Activity
                            @Html.RadioButton("NodeDrawMode", "Role")  Role
                            @Html.RadioButton("NodeDrawMode", "Alternative")  Alternative
                        </div>


                        <div class="form-group" id="OwlModeForm" style="display:none">
                            <label class="control-label">Option Mode</label>
                            @Html.RadioButton("OwlDrawMode", "Follows", new { @checked = true })  Follows
                            @Html.RadioButton("OwlDrawMode", "Precedes")  Precedes
                            @Html.RadioButton("OwlDrawMode", "Decides")  Decides
                            @Html.RadioButton("OwlDrawMode", "IsFollowedBy")  Is Followed by
                            @Html.RadioButton("OwlDrawMode", "IsPrecededBy")  Is Preceded by
                            @Html.RadioButton("OwlDrawMode", "IsDecidedBy")  Is Decided by}
                        </div>

                    </td>
                </tr>
                <tr>

                    <td style="width:20%;height:100%" valign="top">
                        <table style="width:100%;height:100%">
                            <tr>
                                <td>
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <input type="hidden" asp-for="umlDiagram.DiagramId" />

                                    <div id="NodeModeSection">
                                        <div class="form-group" id="ActivitySelectListForm">
                                            <label asp-for="owlRules.Activities" class="control-label"></label>
                                            @Html.DropDownList("ActivitySelectList", new SelectList(Model.owlRules.Activities), new { @class = "form-control" })
                                        </div>
                                        <div class="form-group" id="RoleSelectListForm">
                                            <label asp-for="owlRules.Roles" class="control-label"></label>
                                            @Html.DropDownList("RoleSelectList", new SelectList(Model.owlRules.Roles), new { @class = "form-control" })
                                        </div>
                                        <div class="form-group" id="AlternativeSelectListForm">
                                            <label asp-for="owlRules.Alternatives" class="control-label"></label>
                                            @Html.DropDownList("AlternativeSelectList", new SelectList(Model.owlRules.Alternatives), new { @class = "form-control" })
                                        </div>
                                    </div>

                                    <div id="OwlModeSection">
                                        <div class="form-group" id="FollowsSelectListForm">
                                            <label asp-for="owlRules.Follows" class="control-label"></label>
                                            @Html.DropDownList("FollowsSelectList", new SelectList(Model.owlRules.Follows), new { @class = "form-control" })
                                        </div>
                                        <div class="form-group" id="IsFollowedBySelectListForm">
                                            <label asp-for="owlRules.IsFollowedBy" class="control-label"></label>
                                            @Html.DropDownList("IsFollowedBySelectList", new SelectList(Model.owlRules.IsFollowedBy), new { @class = "form-control" })
                                        </div>
                                        <div class="form-group" id="PrecedesSelectListForm">
                                            <label asp-for="owlRules.Precedes" class="control-label"></label>
                                            @Html.DropDownList("PrecedesSelectList", new SelectList(Model.owlRules.Precedes), new { @class = "form-control" })
                                        </div>
                                        <div class="form-group" id="IsPrecededBySelectListForm">
                                            <label asp-for="owlRules.IsPrecededBy" class="control-label"></label>
                                            @Html.DropDownList("IsPrecededBySelectList", new SelectList(Model.owlRules.IsPrecededBy), new { @class = "form-control" })
                                        </div>
                                        <div class="form-group" id="DecidesSelectListForm">
                                            <label asp-for="owlRules.Decides" class="control-label"></label>
                                            @Html.DropDownList("DecidesSelectList", new SelectList(Model.owlRules.Decides), new { @class = "form-control" })
                                        </div>
                                        <div class="form-group" id="IsDecidedBySelectListForm">
                                            <label asp-for="owlRules.IsDecidedBy" class="control-label"></label>
                                            @Html.DropDownList("IsDecidedBySelectList", new SelectList(Model.owlRules.IsDecidedBy), new { @class = "form-control" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label asp-for="umlDiagram.Name" class="control-label"></label>
                                        <input asp-for="umlDiagram.Name" class="form-control" />
                                        <span asp-validation-for="umlDiagram.Name" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="umlDiagram.ModelId" class="control-label"></label>
                                        <select asp-for="umlDiagram.ModelId" class="form-control" asp-items="ViewBag.ModelId" style="width:100%"> </select>
                                        <span asp-validation-for="umlDiagram.ModelId" class="text-danger"></span>
                                    </div>


                                </td>
                            </tr>
                        </table>
                    </td>
                    <td style="width:calc(100% - 10px); height:100%; float:right" valign="top">
                        <div id="ActivityDiagram" class="ActivityDiagram" style="height:100%; min-height:600px" />
                    </td>
                </tr>
            </table>
        </div>
        <div>
            <textarea readonly style="width:100%;height:50vh;font-family:'Microsoft JhengHei UI';resize:none" id="DrawDataDiagramModel" asp-for="umlDiagram.DrawData"> </textarea>
        </div>

        <div id="NavigationToBackMenu" style="width:100%">
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">myTry</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<environment include="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gojs/1.7.8/go-debug.js"></script>
    <script src="~/js/UmlDiagramModeler.js"></script>
    <script>
        var drawDataString = document.getElementById("DrawDataDiagramModel").textContent;

        var EDrawingMode = {
            Activity: "Activity",
            Alternative: "Alternative",
            Role: "Role",
            Follow: "Follow",
            Precedes: "Precedes"
        };

        var currentSelectListName = "";
        var currentDrawingMode = EDrawingMode.Activity;
        var currentDrawingKey = "";

        diagram_edit.drawDataDiagram = drawDataString;
        //diagram_edit.LoadDrawData();
        //diagram_edit.AddNewNode();

        DiagramDrawModeForm.onclick = function () {
            var radios = document.getElementsByName('DrawMode');
            for (var i = 0, length = radios.length; i < length; i++) {
                if (radios[i].checked) {
                    var form = document.getElementById(radios[i].value + 'ModeForm');
                    var section = document.getElementById(radios[i].value + 'ModeSection');

                    document.getElementById('OwlModeForm').style.display = "none";
                    document.getElementById('OwlModeSection').style.display = "none";      
                    document.getElementById('NodeModeForm').style.display = "none";  
                    document.getElementById('NodeModeSection').style.display = "none";  
                    
                    form.style.display = "inline";
                    section.style.display = "inline";
                    break;
                }
            }
        }

        NodeModeForm.onclick = function () {
            var radios = document.getElementsByName('NodeDrawMode');
            for (var i = 0, length = radios.length; i < length; i++) {
                if (radios[i].checked) {
                    var showList = document.getElementById(radios[i].value + 'SelectListForm');

                    document.getElementById('ActivitySelectListForm').style.display = "none";
                    document.getElementById('AlternativeSelectListForm').style.display = "none";
                    document.getElementById('RoleSelectListForm').style.display = "none";

                    showList.style.display = "inline";
                    SetCurrentDrawingMode(radios[i].value);
                    currentSelectListName = radios[i].value;
                    break;
                }
            }
        }

        OwlModeForm.onclick = function () {
            var radios = document.getElementsByName('OwlDrawMode');
            for (var i = 0, length = radios.length; i < length; i++) {
                if (radios[i].checked) {
                    var showList = document.getElementById(radios[i].value + 'SelectListForm');

                    document.getElementById('FollowsSelectListForm').style.display = "none";
                    document.getElementById('IsFollowedBySelectListForm').style.display = "none";
                    document.getElementById('PrecedesSelectListForm').style.display = "none";
                    document.getElementById('IsPrecededBySelectListForm').style.display = "none";
                    document.getElementById('DecidesSelectListForm').style.display = "none";
                    document.getElementById('IsDecidedBySelectListForm').style.display = "none";

                    showList.style.display = "inline";
                    SetCurrentDrawingMode(radios[i].value);
                    currentSelectListName = radios[i].value;
                    break;
                }
            }
        }

        function SetCurrentDrawingMode(mode) {
            switch (mode) {
                case 'Activity':
                    currentDrawingMode = EDrawingMode.Activity;
                    break;
                case 'Role':
                    currentDrawingMode = EDrawingMode.Role;
                    break;
                case 'Alternative':
                    currentDrawingMode = EDrawingMode.Alternative;
                    break;
                case 'Follows':
                    currentDrawingMode = EDrawingMode.Follow;
                    break;     
                case 'Precedes':
                    currentDrawingMode = EDrawingMode.Precedes;
                    break; 
                case 'IsFollewdBy':
                    currentDrawingMode = EDrawingMode.Precedes;
                    break; 
                case 'IsPrecededBy':
                    currentDrawingMode = EDrawingMode.Follow;
                    break; 
            }            
        }

        function GetCurrentDrawKey() {            
            var e = document.getElementById(currentSelectListName + 'SelectList');
            return e.options[e.selectedIndex].value;            
        }

        function GetCurrentDrawMode() {
            return currentDrawingMode;            
        }

        DiagramDrawModeForm.click();

    </script>
</environment>

DbFirst/DbFirst/Views/UmlDiagrams/Index.cshtml
@model IEnumerable<DbFirst.Models.Northwind.UmlDiagram>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DrawData)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Created)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastModifed)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DrawData)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastModifed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DiagramId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.DiagramId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.DiagramId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>