DbFirst/DbFirst/Controllers/CompareController.cs
using DbFirst.Models;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Xml.Serialization;
using static DiagramMapper.PetriNetMapper;

namespace DbFirst.Controllers
{
    public class CompareController : Controller
    {
        public IActionResult Index()
        {
            var model = new PetriNetModel();
            return View(model);
        }

        public IActionResult Compare(PetriNetModel model)
        {
            XmlSerializer serializer = new XmlSerializer(typeof(DiagramMapper.PetriNetMapper.PetriNet));
            using (TextReader reader = new StringReader(model.RawData))
            {
                PetriNet result = (PetriNet)serializer.Deserialize(reader);
            }
            return View(model);
        }
    }
}

DbFirst/DbFirst/Controllers/OwlModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbFirst.Models.Northwind;
using System.Xml.Linq;
using System.Xml;
using DbFirst.Models;
using Newtonsoft.Json;

namespace DbFirst.Controllers
{
    public class OwlModelsController : Controller
    {
        private readonly NorthwindEntities _context;

        public OwlModelsController(NorthwindEntities context)
        {
            _context = context;
        }

        // GET: OwlModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.OwlModel.ToListAsync());
        }

        // GET: OwlModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var owlModel = await _context.OwlModel
                .SingleOrDefaultAsync(m => m.ModelId == id);
            if (owlModel == null)
            {
                return NotFound();
            }

            return View(owlModel);
        }

        // GET: OwlModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: OwlModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ModelId,Name,ModelData,Created,LastModifed,DefaultDrawData")] OwlModel owlModel)
        {
            if (ModelState.IsValid)
            {            
                var names = _context.OwlModel.Select(m => m.Name.Trim().ToUpper()).ToList();
                if (names.Contains(owlModel.Name.Trim().ToUpper()))
                {
                    return View(owlModel);
                }

                XDocument xml = XDocument.Parse(owlModel.ModelData);
                XNamespace xmlNamespace = XNamespace.Get("http://www.w3.org/2002/07/owl#");

                var classAsertions = xml.Root.Descendants(xmlNamespace + "ClassAssertion").Descendants(xmlNamespace + "Class");
                var Activities = classAsertions.Where(c => c.LastAttribute.Value == "#Activity").Select(xp => xp.Parent).Descendants(xmlNamespace + "NamedIndividual").Select(ni => ni.LastAttribute.Value).ToList();
                var Roles = classAsertions.Where(c => c.LastAttribute.Value == "#Role").Select(xp => xp.Parent).Descendants(xmlNamespace + "NamedIndividual").Select(ni => ni.LastAttribute.Value).ToList();
                var Alternatives = classAsertions.Where(c => c.LastAttribute.Value == "#Alternative").Select(xp => xp.Parent).Descendants(xmlNamespace + "NamedIndividual").Select(ni => ni.LastAttribute.Value).ToList();

                var objectProperties = xml.Root.Elements(xmlNamespace + "ObjectPropertyAssertion").Elements(xmlNamespace + "ObjectProperty").ToList();
                var Follows = OwlModelDoubleDependencies(DetectDoubleDependenciesFromObjectPropery(objectProperties, xmlNamespace, "#Follows"));
                var Precedes = OwlModelDoubleDependencies(DetectDoubleDependenciesFromObjectPropery(objectProperties, xmlNamespace, "#Precedes"));
                var Performs = OwlModelDoubleDependencies(DetectDoubleDependenciesFromObjectPropery(objectProperties, xmlNamespace, "#Performs")).ToList();
                var Decides = OwlModelDoubleDependencies(DetectDoubleDependenciesFromObjectPropery(objectProperties, xmlNamespace, "#Decides"));
                var IsFollowedBy = OwlModelDoubleDependencies(DetectDoubleDependenciesFromObjectPropery(objectProperties, xmlNamespace, "#IsFollowedBy"));
                var IsPrecededBy = OwlModelDoubleDependencies(DetectDoubleDependenciesFromObjectPropery(objectProperties, xmlNamespace, "#IsPrecededBy"));
                var IsPerformed = OwlModelDoubleDependencies(DetectDoubleDependenciesFromObjectPropery(objectProperties, xmlNamespace, "#IsPerformed"));
                var IsDecidedBy = OwlModelDoubleDependencies(DetectDoubleDependenciesFromObjectPropery(objectProperties, xmlNamespace, "#IsDecidedBy"));

                //OwlDependenciesRules rules = new OwlDependenciesRules(Activities, Roles, Alternatives, Follows, Precedes, Decides, IsFollowedBy, IsPrecededBy, IsDecidedBy);
                //owlModel.DefaultDrawData = rules.ToJson();

                _context.Add(owlModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(owlModel);
        }

        // GET: OwlModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var owlModel = await _context.OwlModel.SingleOrDefaultAsync(m => m.ModelId == id);
            if (owlModel == null)
            {
                return NotFound();
            }
            return View(owlModel);
        }

        // POST: OwlModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ModelId,Name,ModelData,Created,LastModifed,DefaultDrawData")] OwlModel owlModel)
        {
            if (id != owlModel.ModelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var modelBeforeUpdate = _context.OwlModel.Where(m => m.ModelId == owlModel.ModelId).Select(nm => new { Created = nm.Created, LastModifed = DateTime.Now, ModelData = nm.ModelData }).FirstOrDefault();
                    owlModel.ModelData = modelBeforeUpdate.ModelData;
                    owlModel.Created = modelBeforeUpdate.Created;
                    owlModel.LastModifed = modelBeforeUpdate.LastModifed;

                    _context.Update(owlModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OwlModelExists(owlModel.ModelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(owlModel);
        }

        // GET: OwlModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var owlModel = await _context.OwlModel
                .SingleOrDefaultAsync(m => m.ModelId == id);
            if (owlModel == null)
            {
                return NotFound();
            }

            return View(owlModel);
        }

        // POST: OwlModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var owlModel = await _context.OwlModel.SingleOrDefaultAsync(m => m.ModelId == id);
            _context.OwlModel.Remove(owlModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OwlModelExists(int id)
        {
            return _context.OwlModel.Any(e => e.ModelId == id);
        }


        private List<string> DetectDoubleDependencies(XDocument xml, XNamespace xmlNamespace, string dependence)
        {
            return xml.Root.Elements(xmlNamespace + "ObjectPropertyAssertion").Elements(xmlNamespace + "ObjectProperty").Where(c => c.LastAttribute.Value == dependence).Select(xp => xp.Parent).Elements(xmlNamespace + "NamedIndividual").Select(ni => ni.LastAttribute.Value).ToList();
        }

        private List<string> DetectDoubleDependenciesFromObjectPropery(List<XElement> xml, XNamespace xmlNamespace, string dependence)
        {
            return xml.Where(c => c.LastAttribute.Value == dependence).Select(xp => xp.Parent).Elements(xmlNamespace + "NamedIndividual").Select(ni => ni.LastAttribute.Value).ToList();
        }

        private List<string> OwlModelDoubleDependencies(List<string> properties)
        {
            List<string> doubleProperties = new List<string>();
            if (properties.Count % 2 == 0)
            {
                for (int i = 0; i < properties.Count; i++)
                {
                    doubleProperties.Add(string.Format("[{0}]:[{1}]", properties[i], properties[++i]));
                }
            }
            return doubleProperties;
        }


    }
}

DbFirst/DbFirst/Controllers/UserAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbFirst.Models.Northwind;

namespace DbFirst.Controllers
{
    public class UserAccountsController : Controller
    {
        private readonly NorthwindEntities _context;

        public UserAccountsController(NorthwindEntities context)
        {
            _context = context;
        }

        // GET: UserAccounts
        public async Task<IActionResult> Index()
        {
            return View(await _context.UserAccount.ToListAsync());
        }

        // GET: UserAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userAccount = await _context.UserAccount
                .SingleOrDefaultAsync(m => m.UserId == id);
            if (userAccount == null)
            {
                return NotFound();
            }

            return View(userAccount);
        }

        // GET: UserAccounts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Name,Password,Email,IsSuperUser,Created,LastModifed")] UserAccount userAccount)
        {
            var UserAccountNames = _context.UserAccount.Select(ua => ua.Name.Trim().ToUpper()).ToList();
            if (ModelState.IsValid && !UserAccountNames.Contains(userAccount.Name.Trim().ToUpper()))
            {
               // userAccount.Created = DateTime.Now;
               // userAccount.LastModifed = DateTime.Now;
               // userAccount.IsSuperUser = false;
                _context.Add(userAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userAccount);
        }

        // GET: UserAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userAccount = await _context.UserAccount.SingleOrDefaultAsync(m => m.UserId == id);
            if (userAccount == null)
            {
                return NotFound();
            }
            return View(userAccount);
        }

        // POST: UserAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Name,Password,Email,IsSuperUser,Created,LastModifed")] UserAccount userAccount)
        {
            if (id != userAccount.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var modelBeforeEdit = _context.UserAccount.Where(ua => ua.UserId == userAccount.UserId).Select(x => new { x.Created, Modifed = DateTime.Now, x.IsSuperUser }).FirstOrDefault();
                    userAccount.Created = modelBeforeEdit.Created;
                    userAccount.LastModifed = modelBeforeEdit.Modifed;
                    userAccount.IsSuperUser = modelBeforeEdit.IsSuperUser;

                    _context.Update(userAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserAccountExists(userAccount.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userAccount);
        }

        // GET: UserAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userAccount = await _context.UserAccount
                .SingleOrDefaultAsync(m => m.UserId == id);
            if (userAccount == null)
            {
                return NotFound();
            }

            return View(userAccount);
        }

        // POST: UserAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userAccount = await _context.UserAccount.SingleOrDefaultAsync(m => m.UserId == id);
            _context.UserAccount.Remove(userAccount);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserAccountExists(int id)
        {
            return _context.UserAccount.Any(e => e.UserId == id);
        }
    }
}

DbFirst/DbFirst/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DbFirst</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/json-formatter/0.7.0/json-formatter.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DbFirst</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="UserAccounts" asp-action="Index">Users</a></li>
                    <li><a asp-area="" asp-controller="UmlDiagrams" asp-action="Index">Diagrams</a></li>
                    <li><a asp-area="" asp-controller="OwlModels" asp-action="Index">OwlModels</a></li>
                    <li><a asp-area="" asp-controller="Compare" asp-action="Index">Comparasion</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - DbFirst</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        @*<script src="https://cdnjs.cloudflare.com/ajax/libs/gojs/1.7.8/go-debug.js"></script>*@
        
    </environment>

    @RenderSection("Scripts", required: false)

   
</body>
</html>